# Generated by Django 3.1.5 on 2021-03-06 19:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CANDIDATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('location', models.CharField(max_length=100, null=True)),
                ('isDeleted', models.BooleanField(default='False')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='INTERVIEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfSubmission', models.DateField()),
                ('timeOfSubmission', models.TimeField(auto_now_add=True)),
                ('languageOfSubmission', models.CharField(max_length=100, null=True)),
                ('isVideo', models.BooleanField(null=True)),
                ('isReportGenerated', models.BooleanField(null=True)),
                ('videoFilePath', models.TextField(null=True)),
                ('videoFileName', models.TextField(null=True)),
                ('audioFilePath', models.TextField(null=True)),
                ('audioFileName', models.TextField(null=True)),
                ('transcriptFilePath', models.TextField(null=True)),
                ('transcriptFileName', models.TextField(null=True)),
                ('eyeContactIndex', models.CharField(max_length=50, null=True)),
                ('smileIndex', models.CharField(max_length=50, null=True)),
                ('lipBiteIndex', models.CharField(max_length=50, null=True)),
                ('faceObstructionIndex', models.CharField(max_length=50, null=True)),
                ('nlpPositivityIndex', models.CharField(max_length=50, null=True)),
                ('voiceConfidenceIndex', models.CharField(max_length=50, null=True)),
                ('reportFilePath', models.TextField(null=True)),
                ('reportFileName', models.TextField(null=True)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Candidate_ID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
