# Generated by Django 3.1.5 on 2021-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='dateOfSubmission',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='isReportGenerated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
