# Generated by Django 3.1.5 on 2021-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210307_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='THRESHOLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateModified', models.DateField(auto_now=True)),
                ('sentimentThresholdLow', models.FloatField(null=True)),
                ('sentimentThresholdMedium', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='isAudioProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='isTranscriptGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='isTranscriptProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='isVideoProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='isReportGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
