# Generated by Django 3.1.5 on 2021-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210420_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='sentimentThresholdLow',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='sentimentThresholdMedium',
        ),
        migrations.AddField(
            model_name='threshold',
            name='metricName',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threshold',
            name='metricThresholdValue',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
